/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/(errors)/403': RouteRecordInfo<
      '/(errors)/403',
      '/403',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/(errors)/no-server-routes': RouteRecordInfo<
      '/(errors)/no-server-routes',
      '/no-server-routes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/area/no-joined': RouteRecordInfo<
      '/area/no-joined',
      '/area/no-joined',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/login': RouteRecordInfo<
      '/auth/login',
      '/auth/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/auth/register': RouteRecordInfo<
      '/auth/register',
      '/auth/register',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/': RouteRecordInfo<
      '/user/',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/action/[id]': RouteRecordInfo<
      '/user/action/[id]',
      '/user/action/:id',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/user/action/create': RouteRecordInfo<
      '/user/action/create',
      '/user/action/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/contact/': RouteRecordInfo<
      '/user/contact/',
      '/user/contact',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/contact/create': RouteRecordInfo<
      '/user/contact/create',
      '/user/contact/create',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/contact/creates/': RouteRecordInfo<
      '/user/contact/creates/',
      '/user/contact/creates',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/contact/creates/merge': RouteRecordInfo<
      '/user/contact/creates/merge',
      '/user/contact/creates/merge',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/contact/creates/recap': RouteRecordInfo<
      '/user/contact/creates/recap',
      '/user/contact/creates/recap',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/contact/creates/review': RouteRecordInfo<
      '/user/contact/creates/review',
      '/user/contact/creates/review',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/contact/search': RouteRecordInfo<
      '/user/contact/search',
      '/user/contact/search',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/user/settings/': RouteRecordInfo<
      '/user/settings/',
      '/user/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/(errors)/403.vue': {
      routes:
        | '/(errors)/403'
      views:
        | never
    }
    'src/pages/(errors)/no-server-routes.vue': {
      routes:
        | '/(errors)/no-server-routes'
      views:
        | never
    }
    'src/pages/area/no-joined.vue': {
      routes:
        | '/area/no-joined'
      views:
        | never
    }
    'src/pages/auth/login.vue': {
      routes:
        | '/auth/login'
      views:
        | never
    }
    'src/pages/auth/register.vue': {
      routes:
        | '/auth/register'
      views:
        | never
    }
    'src/pages/user/index.vue': {
      routes:
        | '/user/'
      views:
        | never
    }
    'src/pages/user/action/[id].vue': {
      routes:
        | '/user/action/[id]'
      views:
        | never
    }
    'src/pages/user/action/create.vue': {
      routes:
        | '/user/action/create'
      views:
        | never
    }
    'src/pages/user/contact/index.vue': {
      routes:
        | '/user/contact/'
      views:
        | never
    }
    'src/pages/user/contact/create.vue': {
      routes:
        | '/user/contact/create'
      views:
        | never
    }
    'src/pages/user/contact/creates/index.vue': {
      routes:
        | '/user/contact/creates/'
      views:
        | never
    }
    'src/pages/user/contact/creates/merge.vue': {
      routes:
        | '/user/contact/creates/merge'
      views:
        | never
    }
    'src/pages/user/contact/creates/recap.vue': {
      routes:
        | '/user/contact/creates/recap'
      views:
        | never
    }
    'src/pages/user/contact/creates/review.vue': {
      routes:
        | '/user/contact/creates/review'
      views:
        | never
    }
    'src/pages/user/contact/search.vue': {
      routes:
        | '/user/contact/search'
      views:
        | never
    }
    'src/pages/user/settings/index.vue': {
      routes:
        | '/user/settings/'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
